ads/urls.py
from django.urls import path, reverse_lazy, re_path

from . import views
app_name = 'ads'

urlpatterns = [
    #path('', views.AdListView.as_view(), name='ad_list'), # I included the tag_view to that url, the next re_path is the upgraded one
    re_path(r'^(?:(?P<tag_name>[\w-]+)/)?$', views.AdListView.as_view(), name='ad_list'),
    path('create', views.AdCreateView.as_view(), name='ad_create'),
    path('<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),  # Fixed the typo in the view name
    path('<int:pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),  # Moved the closing parenthesis to the correct place
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.fav_add, name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.fav_remove, name='ad_unfavorite'),
    #path('<str:tag_name>', views.tag_view, name='tag_view') I gave up on this idea, I stick to DRY and will integrate the tag_view to the AdListView 
]

home/urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name='home'
urlpatterns = [
    path("", TemplateView.as_view(template_name='home/index.html')),
    path('signup/', views.signup, name='signup'),
    path('logout/', LogoutView.as_view(next_page='/ads'), name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # this for serving static files in development mode
import  django.contrib.auth.urls
urlpatterns = [
    path("control-panel/", admin.site.urls),
    path("ads/", include("ads.urls")),
    #path("accounts/", include("django.contrib.auth.urls")), this is very basic auth
    path("", include("home.urls")),
    path("sentiment/", include("sentiment.urls")),
    path('accounts/', include('allauth.urls')),
    path("courses/", include("onlinecourse.urls")),
    path("api/v1/", include("ads.API.urls")),

]


# adding on urlpatterns to serve static file as favicon to my webapp
from django.views.static import serve
import os
from django.conf import settings

urlpatterns += [
    path('favicon.ico',   #When someone accesses '/favicon.ico' on my website, this URL pattern will be matched(which browsers often do automatically to retrieve the site's favicon ).
        serve,            # Use Django's static file serving view for this purpose

        # A dictionary of arguments passed to the `serve` view.
        {
            # This tells the `serve` view which file we want to serve.
            'path': 'favicon.ico',
            'document_root': os.path.join(settings.BASE_DIR, 'mysite/static'),
        }
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/urls.py
from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    LessonListView,
    LessonDetailView,
    QuestionListView,
    enroll,
    submit,
    show_exam_result
)

app_name = "courses"

urlpatterns = [
    path("", CourseListView.as_view(), name="course_list"),
    path("<int:pk>/", CourseDetailView.as_view(), name="course_detail"),
    path("<int:course_id>/lessons/", LessonListView.as_view(), name="lesson_list"),
    path(
        "<int:course_id>/lessons/<int:pk>/",
        LessonDetailView.as_view(),
        name="lesson_detail",
    ),
    path(
        "<int:course_id>/questions/", QuestionListView.as_view(), name="question_list"
    ),
    path("<int:course_id>/enroll/", enroll, name="enroll"),
    path("<int:course_id>/submit/", submit, name="submit"),
    path("<int:course_id>/<int:submission_id>/result/", show_exam_result, name="result"),

]

sentiment/urls.py
from django.urls import path
from . import views
app_name = "sentiment"
urlpatterns = [
    path("", views.sentiment_view, name="sentiment_analyzer")
]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
   pass

home/forms.py
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ('username', 'email', 'password1', 'password2')  # Fields you want on the registration form

home/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login
from .forms import SignUpForm
from django.shortcuts import render, redirect 
from django.urls import reverse
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('ads:ad_list'))  # Replace 'home' with the name of your homepage URL pattern
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>

<head>
    <!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Updated Bootstrap 4 Links -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">






    {% block head %} {% endblock %}

</head>

<body>
    {% block navbar %} {% endblock %}
    <div class="container-fluid">

        {% block welcome %} {% endblock %}
        {% block messages %}
        {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
            {{msg.message}}
        </div>
        {% endfor %}
        {% endif %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
    {% block footer %} {% endblock %}
</body>

</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% load app_tags %}
{% block navbar %}
{% load gravatar %}
<style>
  /* Mobile view */
  @media (max-width: 768px) {
      .custom-navbar .navbar-nav {
          flex-direction: column; /* Stack the nav items vertically */
      }

      .custom-navbar .nav-item {
          text-align: center; /* Center the nav items */
          margin: 5px 0; /* Add some vertical spacing between items */
      }

      .custom-navbar .navbar-brand {
          display: block; /* Make the brand take the full width */
          text-align: center; /* Center the brand text */
      }
  }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark custom-navbar">

  <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav"> <!-- New collapse div for Bootstrap 4 -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == "/" %}active{% endif %}">
        <a class="nav-link" href="/">Home</a>
      </li>
      {% url 'ads' as ads %}
      <li class="nav-item {% if request.get_full_path == ads %}active{% endif %}">
        <a class="nav-link" href="{% url 'ads:ad_list' %}">Ads</a>
      </li>
      <li class="nav-item {% if request.get_full_path == sentiment %}active{% endif %}">
        <a class="nav-link" href="{% url 'sentiment:sentiment_analyzer' %}">Sentiment Analyzer</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'courses:course_list' %}">Courses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/api/v1/">APIs</a>
      </li'>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="{% gravatar_url user.email 40 %}&d=404" alt="{{ user.username }}" class="rounded-circle" onerror="this.onerror=null; this.src='https://www.gravatar.com/avatar/?d=mm&size=40'">

            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'ads:ad_create' %}">Create Ad</a>
              <a class="dropdown-item" href="{% url 'ads:ad_list' %}?my_ads=true">My Ads</a>
              <a class="dropdown-item" href="{% url 'account_logout' %}?next={% url 'ads:ad_list' %}">Logout</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}?next={% url 'ads:ad_list' %}">Login</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'account_signup' %}?next={% url 'ads:ad_list' %}">Signup</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
{% block footer %}
{% include 'partials/_footer.html' %}
{% endblock %}