ads/API/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AdViewSet, CommentViewSet

router = DefaultRouter()
router.register(r'ads', AdViewSet, basename='ads')
router.register(r'comments', CommentViewSet, basename='comments')

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

ads/urls.py
from django.urls import path, reverse_lazy, re_path

from . import views
app_name = 'ads'

urlpatterns = [
    #path('', views.AdListView.as_view(), name='ad_list'), # I included the tag_view to that url, the next re_path is the upgraded one
    re_path(r'^(?:(?P<tag_name>[\w-]+)/)?$', views.AdListView.as_view(), name='ad_list'),
    path('create', views.AdCreateView.as_view(), name='ad_create'),
    path('<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),  # Fixed the typo in the view name
    path('<int:pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),  # Moved the closing parenthesis to the correct place
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.fav_add, name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.fav_remove, name='ad_unfavorite'),
    #path('<str:tag_name>', views.tag_view, name='tag_view') I gave up on this idea, I stick to DRY and will integrate the tag_view to the AdListView 
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # this for serving static files in development mode
import  django.contrib.auth.urls
urlpatterns = [
    path("control-panel/", admin.site.urls),
    path("ads/", include("ads.urls")),
    #path("accounts/", include("django.contrib.auth.urls")), this is very basic auth
    path("", include("home.urls")),
    path("sentiment/", include("sentiment.urls")),
    path('accounts/', include('allauth.urls')),
    path("courses/", include("onlinecourse.urls")),
    path("api/v1/", include("ads.API.urls")),

]


# adding on urlpatterns to serve static file as favicon to my webapp
from django.views.static import serve
import os
from django.conf import settings

urlpatterns += [
    path('favicon.ico',   #When someone accesses '/favicon.ico' on my website, this URL pattern will be matched(which browsers often do automatically to retrieve the site's favicon ).
        serve,            # Use Django's static file serving view for this purpose

        # A dictionary of arguments passed to the `serve` view.
        {
            # This tells the `serve` view which file we want to serve.
            'path': 'favicon.ico',
            'document_root': os.path.join(settings.BASE_DIR, 'mysite/static'),
        }
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.db import models
from taggit.managers import TaggableManager
# Create your models here.
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.conf import settings
from datetime import timedelta
import random

class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # here we refer to the current user model in my settings.py (could be custom user model defined in settings.py)
        
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_ads')
    tags = TaggableManager()
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title
    # to generate semi-random updated_at in my scripts!
    def random_updated_at(self):
        self.updated_at = self.created_at + timedelta(days=random.randint(0, 15), hours=random.randint(0, 24))

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self) :
        return f"{self.user.username} likes {self.ad.title}"
            

ads/forms.py
from django import forms
from ads.models import Ad, Comment
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize


# Create the form class.
class AdCreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024 # 2MB
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+str(max_upload_limit_text))
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Ad
        fields = ['title', 'price', 'text','tags', 'picture']  # Picture is manual(because it is not ImageField)

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return cleaned_data
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit+" bytes")
        return cleaned_data
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        model_instance = super().save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = model_instance.picture
        if isinstance(f, InMemoryUploadedFile):  # if the image data is in memory and not in file sys that means it is fresh
            bytearr = f.read()
            model_instance.content_type = f.content_type
            model_instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            model_instance.save()
            self.save_m2m()
        return model_instance
    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)

class CommentForm(forms.ModelForm):
    text = forms.CharField(
        label='Comments',
        widget=forms.TextInput(attrs={'placeholder': 'Add your comment here...'})
    )
    
    class Meta:
        model = Comment
        fields = ['text']

ads/API/views.py
from rest_framework import viewsets
from ads.models import Ad, Comment
from rest_framework.decorators import action
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from .filters import AdFilter
from .serializers import AdSerializer, CommentSerializer, AdDetailSerializer, CommentDetailSerializer


class AdViewSet(viewsets.ModelViewSet):
    queryset = Ad.objects.all().order_by('-created_at') 
    serializer_class = AdSerializer
    filterset_class = AdFilter

    def get_serializer_class(self): 
        # Use the DetailedPostSerializer for the "retrieve" action
        if self.action == 'retrieve':
            # When accessing a specific object, use the DetailedPostSerializer
            return AdDetailSerializer
        # For other actions, use the default serializer class
        return super().get_serializer_class()

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
        #return super().perform_create(serializer)

    @action(detail=True, methods=['get'], url_path='comments')
    def comments(self, request, pk=None):
        ad = get_object_or_404(Ad.objects.prefetch_related('comment_set'), pk=pk)
        comments = ad.comment_set.all() # will not hit the DB.
        page = self.paginate_queryset(comments)  # uses the ViewSET pagination class
        if page:
            serializer = CommentSerializer(page, many=True)
            return Response(serializer.data)
        serializer = CommentSerializer(comments, many=True)  
        return Response(serializer.data)

    @action(methods=[ 'get' ], detail=False, name='My Ads', url_path='my-ads',)
    def my_ads(self, request):
        if request.user.is_authenticated:
            ads = Ad.objects.filter(owner=request.user).order_by('-created_at')
            page = self.paginate_queryset(ads)
            if page:
                serializer = AdSerializer(page, many=True)
                return Response(serializer.data)

            serializer = AdSerializer(ads, many=True)
            return Response(serializer.data)
        else:
            return Response({'error': 'sign in to see your ads'}, status=401)


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all().order_by('-created_at') 
    serializer_class = CommentSerializer

    def get_serializer_class(self):
        if self.action == 'retrieve':
            return CommentDetailSerializer
        return super().get_serializer_class()

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
        return super().perform_create(serializer)

    @action(methods=[ 'get' ], detail=False, name ='My Comments', url_path='my-comments',)
    def my_comments(self, request):
        if request.user.is_authenticated:
            comments = Comment.objects.filter(owner=request.user).order_by('-created_at')
            page = self.paginate_queryset(comments)
            if page:
                serializer = CommentSerializer(page, many=True)
                return Response(serializer.data)
            serializer = CommentSerializer(comments, many=True)
            return Response(serializer.data)
        else:
            return Response({'error': 'sign in to see your comments'}, status=401)

ads/views.py
from typing import Any
from django.db import models
from django.db.models import Q
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from django.views import generic 
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ad, Comment, Fav
from .forms import AdCreateForm, CommentForm


class AdListView(generic.ListView):
    model = Ad 
    template_name = 'ads/ad_list.html'
    context_object_name = 'ad_list' 
    search_fields = ['title', 'tags']
    paginate_by = 20
    
    def get_queryset(self) -> QuerySet[Any]:
        query_set =  super().get_queryset()
        search = self.request.GET.get('search')
        tag_name = self.kwargs.get('tag_name', None)
        my_ads = self.request.GET.get('my_ads', None)
        if search:  
            query_set = Ad.objects.filter(Q(title__icontains=search) | Q(tags__name__icontains=search))
            
        elif tag_name : 
            query_set = Ad.objects.filter(tags__name__iexact=tag_name)
            
        elif my_ads:
            query_set = Ad.objects.filter(owner=self.request.user)
         
        return query_set.order_by('id')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # If the user is authenticated, fetch their favorite ads
        if self.request.user.is_authenticated:
            favorite_ads = Fav.objects.filter(user=self.request.user).values_list('ad_id', flat=True)
            context['favorites'] = list(favorite_ads)
        else:
            context['favorites'] = []

        return context
    
    
    
    
class AdCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ad
    form_class = AdCreateForm
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        self.object =  form.save()  # self.object is convention in Django.
        form.save_m2m()
        return super().form_valid(form)

class AdUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ad 
    form_class = AdCreateForm 
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_list')
    def form_valid(self, form: BaseModelForm) :
        form.instance.owner = self.request.user
        return super().form_valid(form)
        
class AdDetailView(generic.DeleteView):
    model = Ad
    template_name = "ads/ad_detail.html"
    def get(self, request, pk) :
        x = get_object_or_404(Ad, id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }

        return render(request, self.template_name, context)
        
        
class AdDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ad 
    context_object_name = 'ad'           # no need to add template_name if I followed the convention.
    success_url = reverse_lazy('ads:ad_list')
def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    if ad.content_type:
        response = HttpResponse()
        response['Content-Type'] = ad.content_type
        response['Content-Length'] = len(ad.picture)
        response.write(ad.picture)
        return response
        
    
class CommentCreateView(LoginRequiredMixin, generic.CreateView):
    model = Comment
    def post(self, request: HttpRequest, *args: str, **kwargs: Any):
        form = CommentForm(request.POST)                                # we can use form_valid and  get_succsess_url instead 
        current_ad = Ad.objects.get(id=self.kwargs['pk'])
        if form.is_valid():
            to_save_model_instance= form.save(commit=False)
            to_save_model_instance.owner = self.request.user 
            to_save_model_instance.ad = current_ad 
            
            to_save_model_instance.save()
        else :
            form = CommentForm()  
            
        return redirect(reverse('ads:ad_detail', kwargs={'pk': self.kwargs['pk']}))
    
    
class CommentDeleteView(LoginRequiredMixin, generic.DeleteView): 
    model = Comment
    template_name = "ads/comment_confirm_delete.html"
    def get_queryset(self):
        query = Comment.objects.filter(owner = self.request.user)
        return query
    def get_success_url(self):
        ad = self.object.ad   # the object I deleted
        return reverse('ads:ad_detail', args=[ad.id])
    
    
    
def fav_add(request, pk):
    if request.method== 'POST' and request.user.is_authenticated:
        ad = get_object_or_404(Ad, id=pk)
        if not Fav.objects.filter(ad=ad, user=request.user).exists():
            
            fav = Fav(ad=ad, user=request.user) 
            fav.save()
            return JsonResponse({'message':'success'}, status=200)
        else : 
            return JsonResponse({'error': 'Already favorited'}, status=400)
             
    else: 
        return JsonResponse({'error': 'not post or user not authen'}, status=400)
    
  
def fav_remove(request, pk):
    if request.method == 'POST' and request.user.is_authenticated:
        ad = get_object_or_404(Ad, id=pk)
        
        # Check if the fav record exists
        fav_record = Fav.objects.filter(ad=ad, user=request.user).first()
        
        if fav_record:
            fav_record.delete()
            return JsonResponse({'message':'success'}, status=200)
    else: 
        return JsonResponse({'error': 'not post or user not authen'}, status=400)
    
    
    
    
from taggit.models import Tag

def tag_view(request, tag_name):
    # You can use the `tagged_with` method provided by django-taggit
    query_set = Ad.objects.filter(tags__name__iexact=tag_name)
    context = {'ad_list': query_set}
    if request.user.is_authenticated:
        favorite_ads = Fav.objects.filter(user=request.user).values_list('ad_id', flat=True)
        context['favorites'] = list(favorite_ads)
    return render(request, 'ads/ad_list.html', context=context)

ads/templates/ads/ad_confirm_delete.html
{% extends 'base_menu.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card border-danger mb-3">
                <div class="card-header bg-danger text-white">Delete Ad Confirmation</div>
                <div class="card-body">
                    <h4 class="card-title">Are you sure you want to delete this ad?</h4>
                    <hr>
                    <p class="card-text font-weight-bold">Title: <span class="font-weight-normal">{{ ad.title }}</span></p>
                    <hr>
                    <p class="card-text">{{ ad.text }}</p>
                    <form action="" method="POST" class="mt-3">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Yes, delete.">
                        <a href="{% url 'ads:ad_detail' ad.id %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block head %}
{% load static %}
<style>
    /* Image Frame */
    .img-container {
        border: 4px solid #e9ecef; /* Adjusted to Bootstrap's light gray */
        padding: 10px;
        margin: 10px 0;
        width: 300px;
    }
    .img-container img {
        max-width: 100%;
        height: auto;
    }

    /* Comment styling */
    .comment-container {
        background-color: #f7f7f7;
        padding: 1rem; /* Consistent with Bootstrap's padding notation */
        margin: 1rem 0;
        border: 1px solid #e9ecef; /* Bootstrap's light gray */
        border-radius: 4px;
    }
    .comment-actions {
        font-size: 0.8rem;
        margin-top: .5rem; /* Consistent with Bootstrap's margin notation */
    }
    .comments-section {
    max-height: 400px; /* adjust this value as needed */
    overflow-y: auto;  /* vertical scrollbar */


    }
    .tag {
    display: inline-block;
    background-color: #e9e9e9; /* Light grey background */
    color: #333; /* Darker grey text */
    padding: 6px 12px; /* Slightly larger padding */
    margin-right: 5px;
    border-radius: 15px; /* Rounded corners */
    text-decoration: none; /* Remove underline if it's a link */
    transition: background-color 0.3s, transform 0.3s; /* Smooth transition for hover effects */

    }

    .tag:hover {
    background-color: #d0d0d0; /* Slightly darker grey on hover */
    transform: scale(1.05); /* Slightly enlarge the tag on hover */
    cursor: pointer; /* Change cursor to indicate clickability */
    }
    .ad-content {
    display: flex;
    align-items: start; /* Align items to the top */
    gap: 1rem; /* Space between the image and the content */
    }

/* Make the image appear on the right */
.ad-image {
    order: 2;
    }

</style>
{% endblock %}

{% block content %}
<div class="mb-4">
    <div class="float-right text-muted">
        (last update: {{ ad.updated_at|naturaltime }})
        {% if ad.owner == user %}
            <a href="{% url 'ads:ad_update' ad.id %}" class="text-primary ml-2"><i class="fas fa-pencil-alt"></i></a>
            <a href="{% url 'ads:ad_delete' ad.id %}" class="text-danger ml-2"><i class="fas fa-trash-alt"></i></a>
        {% endif %}
    </div>
    <h1 class="mb-4">{{ ad.title }}</h1>
    <p>
        {{ ad.text }}
    </p>
    <p>
        Price: <strong>${{ ad.price|floatformat:2 }}</strong>
    </p>
    {% if ad.tags.all %}
    <p>Tags:
        {% for tag in ad.tags.all %}
          <a href="{% url 'ads:ad_list' tag_name=tag.name %}"><strong><span class="tag">{{ tag.name }}</span></strong></a>
        {% endfor %}
    </p>
    {% endif %}

    <div class="ad-image">
    {% if ad.content_type %}
    <div class="img-container float-right">
        <img src="{% url 'ads:ad_picture' ad.id %}" alt="{{ ad.title }}" onclick="document.getElementById('overlay').style.display = 'block';">
    </div>
    <div style="clear:right;"></div>
    {% endif %}
    </div>

    <h3 class="mt-4">Comments:</h3>
    <div class="comments-section">
        {% for comment in comments %}
        <div class="comment-container mb-3"> <!-- Added margin-bottom for spacing between comments -->
            <div class="d-flex flex-row align-items-center mb-2"> <!-- Added margin-bottom for spacing between the header and the comment text -->
                <img src="{% static 'images/person.png' %}" alt="person image">
                <p class="big mb-0">({{comment.owner}})</p>
            </div>
            <p class="mb-2">{{ comment.text }}</p> <!-- Added margin-bottom for spacing between the comment text and the actions -->
            <div class="comment-actions">
                <span class="text-muted">{{ comment.updated_at }}</span>
                {% if user == comment.owner %}
                    <a href="{% url 'ads:ad_comment_delete' comment.id %}" class="text-danger ms-2"><i class="fas fa-trash-alt"></i> Delete</a> <!-- Added margin-start for spacing between the date and the delete link -->
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>

    {% if user.is_authenticated %}
    <div class="mt-4">
        <h4>Add a Comment:</h4>
        <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <div class="mt-2">
                <input type="submit" value="Add comment!" class="btn btn-primary">
                <button type="button" class="btn btn-secondary" onclick="window.location.href='{% url 'ads:ad_list' %}';">All Ads</button>
            </div>
        </form>
    </div>
    {% endif %}

    <p class="mt-4">
        <a href="{% url 'ads:ad_list' %}" class="btn btn-link">All ads</a>
    </p>
</div>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% block content %}
{% csrf_token %}
{% load humanize %}
<h1>Ads</h1>

<style>
    .custom-search .form-control {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
        line-height: 1.5;
    }
    .custom-search .btn {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
        line-height: 1.5;
    }
    .ads-container {
    max-height: 420px;
    overflow-y: auto;
    width: 100%;
    scroll-behavior: smooth;
    }

    .pagination {
    font-weight: bold;
    margin-bottom: 10px;
    display: flex;
    justify-content: center; /* center the pagination elements horizontally */
    }

    .pagination .step-links {
        display: flex;
        align-items: center;
        gap: 10px; /* adds space between direct children elements */
    }

    .pagination a {
        margin: 0 5px; /* horizontal spacing between links */
        padding: 3px 8px; /* internal spacing within each link */
        border: 1px solid #ccc; /* optional, to add a border around each link */
        text-decoration: none; /* remove underline from links */
    }

    .pagination .current {
        margin: 0 15px; /* larger horizontal spacing for the page counter */
    }




</style>

<div class="float-right mb-2"> <!-- I added a slight margin-bottom for the search bar -->
    <form method="get" class="form-inline custom-search"> 
        <div class="input-group">
            <input type="text" class="form-control" name="search" label="you can search by title or tag" placeholder="Search Ads ...">
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> Search</button>
            </div>
        </div>
    </form>
</div>

<div class="ads-container">
    <div class="alert alert-info" role="alert">
        Currently available ad tags to search for: (<strong>movies, drugs</strong>)
    </div>
    {% if ad_list %}
    <ul class="list-group">
      {% for ad in ad_list %}
        <li class="list-group-item">
            <a href="{% url 'ads:ad_detail' ad.id %}">{{ ad.title }}</a>
            {% if ad.owner == user %}
            (<a href="{% url 'ads:ad_update' ad.id %}" class="text-primary"><i class="fas fa-edit"></i> Edit</a> |
            <a href="{% url 'ads:ad_delete' ad.id %}" class="text-danger"><i class="fas fa-trash-alt"></i> Delete</a>)
            {% endif %}
        
            {% if user.is_authenticated %}
            <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
            <a href="#" onclick="favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;" {% if ad.id not in favorites %} style="display: none;" {% endif %} id="favorite_star_{{ad.id}}">
            <span class="fa-stack" style="vertical-align: middle;">
            <i class="fas fa-star fa-stack-1x" style="color: orange;"></i> <!-- FontAwesome 5 icon -->
            </span>
            </a>
            <!-- the second href -->
            <a href="#" onclick="favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;" {% if ad.id in favorites %} style="display: none;" {% endif %} id="unfavorite_star_{{ad.id}}">
            <span class="fa-stack" style="vertical-align: middle;">
            <i class="far fa-star fa-stack-1x"></i> <!-- FontAwesome 5 icon -->
            </span>
            </a>
            {% endif %}
            ({{ad.created_at|naturaltime}})
        </li>
    </ul>
      {% endfor %}
 
</div>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?search={{ request.GET.search|default:'' }}&page=1">&laquo; first</a>
        <a href="?search={{ request.GET.search|default:'' }}&page={{ page_obj.previous_page_number }}">{{ page_obj.number|add:'-1' }}</a>
        {% endif %}

        <span class="current">
             {{ page_obj.number }}
        </span>

        {% if page_obj.has_next %}
            <a href="?search={{ request.GET.search|default:'' }}&page={{ page_obj.next_page_number }}">{{ page_obj.number|add:'1' }}</a>
            <a href="?search={{ request.GET.search|default:'' }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>



{% else %}
  <p>There are no ads in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'ads:ad_create' %}" class="btn btn-success"><i class="fas fa-plus"></i> Add an Ad</a>
{% if user.is_authenticated %}
<a href="{% url 'account_logout' %}?next={% url 'ads:ad_list' %}" class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Logout</a>
{% else %}
<a href="{% url 'account_login' %}?next={% url 'ads:ad_list' %}" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Login</a>
{% endif %}
</p>
<script>
function toggleInlineDisplay(star_id) {
    var elem = document.getElementById(star_id);
    if(window.getComputedStyle(elem).display == "inline") {
        elem.style.display = 'none';
        elem.dataset.previousDisplay = 'inline';
    } else if(window.getComputedStyle(elem).display == "block") {
        elem.style.display = 'none';
        elem.dataset.previousDisplay = 'block';
    } else {
        console.log('prev', elem.dataset.previousDisplay);
        if ( typeof elem.dataset.previousDisplay == 'string' ) {
            elem.style.display = elem.dataset.previousDisplay
        } else {
            elem.style.display = 'inline';
        }
    }
}

function favPost(url, ad_id) {
    console.log('POSTing to', url);
    const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    fetch(url, { method: 'POST',headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrfToken  // Include the CSRF token in the request header
        }, body: '{}' } )
    .then((response) => {
        console.log(url, 'finished');
        toggleInlineDisplay("unfavorite_star_"+ad_id);
        toggleInlineDisplay("favorite_star_"+ad_id);
    }).catch((error) => {
        alert('Url failed with '+error+' '+url);
    });
}
</script>
{% endblock %}