ads/urls.py
from django.urls import path, reverse_lazy, re_path

from . import views
app_name = 'ads'

urlpatterns = [
    #path('', views.AdListView.as_view(), name='ad_list'), # I included the tag_view to that url, the next re_path is the upgraded one
    re_path(r'^(?:(?P<tag_name>[\w-]+)/)?$', views.AdListView.as_view(), name='ad_list'),
    path('create', views.AdCreateView.as_view(), name='ad_create'),
    path('<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),  # Fixed the typo in the view name
    path('<int:pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('<int:pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),  # Moved the closing parenthesis to the correct place
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:ad_list')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.fav_add, name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.fav_remove, name='ad_unfavorite'),
    #path('<str:tag_name>', views.tag_view, name='tag_view') I gave up on this idea, I stick to DRY and will integrate the tag_view to the AdListView 
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # this for serving static files in development mode
import  django.contrib.auth.urls
urlpatterns = [
    path("control-panel/", admin.site.urls),
    path("ads/", include("ads.urls")),
    #path("accounts/", include("django.contrib.auth.urls")), this is very basic auth
    path("", include("home.urls")),
    path("sentiment/", include("sentiment.urls")),
    path('accounts/', include('allauth.urls')),
    path("courses/", include("onlinecourse.urls")),
    path("api/v1/", include("ads.API.urls")),

]


# adding on urlpatterns to serve static file as favicon to my webapp
from django.views.static import serve
import os
from django.conf import settings

urlpatterns += [
    path('favicon.ico',   #When someone accesses '/favicon.ico' on my website, this URL pattern will be matched(which browsers often do automatically to retrieve the site's favicon ).
        serve,            # Use Django's static file serving view for this purpose

        # A dictionary of arguments passed to the `serve` view.
        {
            # This tells the `serve` view which file we want to serve.
            'path': 'favicon.ico',
            'document_root': os.path.join(settings.BASE_DIR, 'mysite/static'),
        }
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/urls.py
from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    LessonListView,
    LessonDetailView,
    QuestionListView,
    enroll,
    submit,
    show_exam_result
)

app_name = "courses"

urlpatterns = [
    path("", CourseListView.as_view(), name="course_list"),
    path("<int:pk>/", CourseDetailView.as_view(), name="course_detail"),
    path("<int:course_id>/lessons/", LessonListView.as_view(), name="lesson_list"),
    path(
        "<int:course_id>/lessons/<int:pk>/",
        LessonDetailView.as_view(),
        name="lesson_detail",
    ),
    path(
        "<int:course_id>/questions/", QuestionListView.as_view(), name="question_list"
    ),
    path("<int:course_id>/enroll/", enroll, name="enroll"),
    path("<int:course_id>/submit/", submit, name="submit"),
    path("<int:course_id>/<int:submission_id>/result/", show_exam_result, name="result"),

]

onlinecourse/models.py
from django.db import models
from django.db.models import Avg
from django.conf import settings

# Create your models here.


class Learner(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    HUMAN = "HB"
    ROBOT = "RB"
    ALIEN = "AL"
    choices = (
        (HUMAN, "Human"),
        (ROBOT, "Robot"),
        (ALIEN, "Alien"),
    )
    occupation = models.CharField(
        max_length=20, choices=choices, default=HUMAN, null=False
    )
    social_link = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username + ", " + self.occupation


class Instructor(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_time = models.BooleanField(default=False)
    total_learners = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username


class Course(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="course_images/", blank=True, default="course_images/defaultcourse.jpg")
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructor = models.ManyToManyField(Instructor)
    learners = models.ManyToManyField(Learner, through="Enrollment")
    total_enrollment = models.IntegerField(default=0, null=True, blank=True)
    rating = models.FloatField(null=True, blank=True)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ", " + str(self.total_enrollment)

    def save(self, *args, **kwargs):
        super(Course, self).save(*args, **kwargs)
        self.total_enrollment = self.learners.count()
        self.rating = self.enrollment_set.aggregate(Avg("rating"))[
            "rating__avg"
        ]  # the result is a dictionary
        # Save the instance again with specific fields to avoid recursion
        super(Course, self).save(update_fields=['total_enrollment', 'rating']) 

class CourseInstructor(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    instructor = models.ForeignKey('Instructor', on_delete=models.CASCADE)  
    
    class Meta:
        unique_together = ('course', 'instructor')

class Lesson(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)


class Enrollment(models.Model):
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField(default=5.00)

    class Meta:
        unique_together = ('learner', 'course')

class Question(models.Model):
    question = models.CharField(max_length=1000)
    grade = models.IntegerField(default=1)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.question[:15]

    def is_graded(self, selected_choices):
        correct_choices_ids = sorted(list(self.choice_set.filter(is_correct=True).order_by('id').values_list('id', flat=True)))
        selected_correct_ids = sorted(list(self.choice_set.filter(is_correct=True, id__in=selected_choices).order_by('id').values_list('id', flat=True)))
        return correct_choices_ids == selected_correct_ids
        

class Choice(models.Model):
    text = models.CharField(max_length=50)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:15]

class Submission(models.Model):
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)

onlinecourse/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Sum
from .models import (
    Course,
    Lesson,
    Instructor,
    Enrollment,
    Learner,
    Question,
    Submission,
    Choice,
)


class CourseListView(ListView):
    model = Course
    template_name = "onlinecourse/course_list.html"
    context_object_name = "courses"
    # I will add list of each course intructors to the context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lst_of_instructores = []
        lst_of_instructors_querysets = [course.instructor.all() for course in context["courses"]]
        for query in lst_of_instructors_querysets:
            for instructor in query:
                lst_of_instructores.append(instructor.user.username)

        context["instructors"] = lst_of_instructores
        context["str_user"] = str(self.request.user) # str_user to prevent confusion with user
        # the self.request.user may not be a learner
        try : 
            learner = Learner.objects.get(user=self.request.user)
            context["enrolled_courses_ids"] = Enrollment.objects.filter(learner=learner).values_list('course', flat=True)
        except :
            context["enrolled_courses_ids"] = []

        return context
    #    context["courses"] = Course.objects.all()

class CourseDetailView(DetailView):
    model = Course
    template_name = "onlinecourse/course_detail.html"
    context_object_name = "course"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_lessons"] = Lesson.objects.filter(course=self.object).exists()
        context["is_questions"] = Question.objects.filter(course=self.object).exists()
        return context


class LessonListView(ListView):
    model = Lesson
    template_name = "onlinecourse/lesson_list.html"
    context_object_name = "lessons"

    def get_queryset(self):
        return Lesson.objects.filter(course__id=self.kwargs["course_id"])


class LessonDetailView(DetailView):
    model = Lesson
    template_name = "onlinecourse/lesson_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["course"] = Course.objects.get(id=self.kwargs["course_id"])
        return context


class QuestionListView(ListView):
    model = Question
    template_name = "onlinecourse/question_list.html"

    def get_queryset(self):
        return Question.objects.filter(course__id=self.kwargs["course_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["course_id"] = self.kwargs["course_id"]
        context["course"] = Course.objects.get(id = self.kwargs["course_id"])
        return context


def extract_answers(request):
    answers = []
    for key, value in request.POST.items():
        if key.startswith("choice"):
            choice_id = int(value)
            answers.append(choice_id)
    return answers


def submit(request, course_id):
    course = Course.objects.get(pk=course_id)
    enrollment = Enrollment.objects.get(
        learner__user=request.user, course__id=course_id
    )
    submission = Submission(enrollment=enrollment)
    submission.save()
    choices = extract_answers(request)
    submission.choices.set(choices)
    submission_id = submission.id
    return HttpResponseRedirect(
        reverse("courses:result", args=(course_id, submission_id))
    )


def show_exam_result(request, course_id, submission_id):
    questions = Question.objects.filter(course__id=course_id)
    submission = get_object_or_404(Submission, pk=submission_id)
    choices = submission.choices.all()
    total_grade = 0
    for question in questions:
        selected_choices = choices.filter(question=question)
        if question.is_graded(selected_choices):
            total_grade += question.grade
    total_available_grade = questions.aggregate(Sum("grade"))["grade__sum"]
    context = {}
    context["total_grade"] = total_grade
    context["questions"] = questions
    context["choices"] = choices
    context["grade"] = round((total_grade / total_available_grade)*100) if total_available_grade != 0 else 0
    return render(request, "onlinecourse/exam_result.html", context)


def enroll(request, course_id):
    if request.user.is_authenticated:
        course = Course.objects.get(pk=course_id)
        learner, created = Learner.objects.get_or_create(user=request.user)
        enrollment, created = Enrollment.objects.get_or_create(learner=learner, course=course)
        enrollment.save()
        course.save() # to update the number of learners in the course

        return HttpResponseRedirect(reverse("courses:course_list"))
    else :
        return HttpResponseRedirect(reverse("account_login"))

onlinecourse/templates/onlinecourse/course_detail.html
{% extends "base_menu.html" %} 

{% block content %} 
<div class="container">
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="{{ course.image.url }}" class="card-img" alt="{{ course.name }}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ course.name }}</h5>
                    <p class="card-text">{{ course.description }}</p>
                    <p class="card-text"><small class="text-muted">Total Enrollments: {{ course.total_enrollment }}</small></p>
                    {% if is_lessons %}
                        <a href="{% url 'courses:lesson_list' course.id %}" class="btn btn-primary">Lessons</a>
                    {% else %}
                        <p>No lessons are available.</p>    
                    {% endif %}
                    {% if is_questions %}
                        <a href="{% url 'courses:question_list' course.id %}" class="btn btn-secondary">Questions</a>
                    {% else %}
                        <p>No questions are available.</p>    
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

onlinecourse/templates/onlinecourse/course_list.html
{% extends "base_menu.html" %} 

{% block content %}
  {% if courses %}
    <div class="container">
      <div class="card-deck">
        {% for course in courses %}
          <div class="card" style="width: 36rem;">
            {% if course.image %}
              <img class="card-img-left" src="{{ course.image.url }}" width="240px" height="240px" alt="Course image">
            {% endif %}
            <div class="card-body bg-light">
              <h5 class="card-title">{{ course.name }}, <span class="text-success">{{ course.total_enrollment }} enrolled</span></h5>
              <p class="card-text">{{ course.description }}</p>
              {% if str_user in instructors %}
                <a href="{% url 'courses:course_detail' course.id %}" class="btn btn-primary">View</a>
              {% else %}
                {% if course.id in enrolled_courses_ids  %}
                  <a href="{% url 'courses:course_detail' course.id %}" class="btn btn-primary">Enter</a>
                {% else %}
                  <form action="{% url 'courses:enroll' course.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-primary" type="submit" value="Enroll">
                  </form>
                {% endif %}
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% else %}
    <p>No courses are available.</p>
  {% endif %}
{% endblock %}

onlinecourse/templates/onlinecourse/exam_result.html
{% extends "base_menu.html" %}
{% block content %}
<div class="container-fluid">
    {% if grade > 80 %}
    <div class="alert alert-success">
        <b>Congratulations, {{ user.first_name }}!</b> You have passed the exam and completed the course with a score of {{ grade }}/100.
    </div>
    {% else %}
    <div class="alert alert-danger">
        <b>Failed</b> Sorry, {{ user.first_name }}! You have failed the exam with a score of {{ grade }}/100.
    </div>
    {% endif %}
    <div class="card-columns-vertical mt-1">
        <h5 class="">Exam results</h5>
        {% for question in questions %}
        <div class="card mt-1">
            <div class="card-header"><h5>{{ question.question }}</h5></div>
            <div class="form-group">
                <b>Your Choices: </b>
                {% for choice in choices %}
                {% if choice.question.id == question.id %}
                
                    <div class="form-check">
                        {% if choice.is_correct %}
                            <div class="text-success">{{ choice.text }}</div>
                        {% elif choice in choices %}
                            <div class="text-danger">{{ choice.text }}</div>

                        {% endif %}
                    </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

onlinecourse/templates/onlinecourse/lesson_detail.html
{% extends "base_menu.html" %} 
{% block content %}
   
    {{object.title}}
    {{object.description}}
    {{object.course}}
    
{% endblock% }

onlinecourse/templates/onlinecourse/lesson_list.html
{% extends "base_menu.html" %} 
{% block content %}
    {% if lessons %}
        {% for lesson in lessons %}
            <div class="card mt-1">
                <div class="card-header"><h5>Lesson {{lesson.order|add:1}}: {{lesson.title}}</h5></div>
                <div class="card-body">{{lesson.description}}</div>
            </div>
        {% endfor %}
    {% else %}
        <p>No lessons are available.</p>
    {% endif %}
{% endblock %}

onlinecourse/templates/onlinecourse/question_list.html
{% extends "base_menu.html" %} 
{% block content %}
    <div class="container-fluid">
        <h2>{{ course.name }}</h2>
        {{course_id}}
        {% if user.is_authenticated %}
        </br>
        <button class="btn btn-primary btn-block" data-toggle="collapse" data-target="#exam">Start Exam</button>
        <div id="exam" class="collapse">
            <form id="questionform" action="{% url 'courses:submit' course_id %}" method="POST">
                {% for question in course.question_set.all %}
                <div class="card mt-1">
                    <div class="card-header">
                        <h5>{{ question.question }}</h5>
                    </div>
                    {% csrf_token %}
                    <div class="form-group">
                        {% for choice in question.choice_set.all %}
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" name="choice_{{choice.id}}" class="form-check-input"
                                    id="{{choice.id}}" value="{{choice.id}}">{{ choice.text }}
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                <input class="btn btn-success btn-block" type="submit" value="Submit">
            </form>
        </div>
    {% endif %}      
</div>
{% endblock %}